// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFDWOsT272PyWMa7k89pijXg9WG1qPGM',
    appId: '1:261644401970:web:0ca1cb62d9ef62c902eb2b',
    messagingSenderId: '261644401970',
    projectId: 'lab4-53f47',
    authDomain: 'lab4-53f47.firebaseapp.com',
    storageBucket: 'lab4-53f47.firebasestorage.app',
    measurementId: 'G-XVX951M8NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJCS1uCyDO5Bb7AY7XusYfRwesjV0HQfo',
    appId: '1:261644401970:android:afcfd783c01d638702eb2b',
    messagingSenderId: '261644401970',
    projectId: 'lab4-53f47',
    storageBucket: 'lab4-53f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwzuqylzuNZxc1ztXueN3muFiHLKu2hRo',
    appId: '1:261644401970:ios:6221652c28b75d8902eb2b',
    messagingSenderId: '261644401970',
    projectId: 'lab4-53f47',
    storageBucket: 'lab4-53f47.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwzuqylzuNZxc1ztXueN3muFiHLKu2hRo',
    appId: '1:261644401970:ios:6221652c28b75d8902eb2b',
    messagingSenderId: '261644401970',
    projectId: 'lab4-53f47',
    storageBucket: 'lab4-53f47.firebasestorage.app',
    iosBundleId: 'com.example.lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxFDWOsT272PyWMa7k89pijXg9WG1qPGM',
    appId: '1:261644401970:web:14d6a5a24a74ed7902eb2b',
    messagingSenderId: '261644401970',
    projectId: 'lab4-53f47',
    authDomain: 'lab4-53f47.firebaseapp.com',
    storageBucket: 'lab4-53f47.firebasestorage.app',
    measurementId: 'G-QF8QFWVTXJ',
  );
}
